### ISSUE TITLE
생년월일 optional 하게 수정

### ISSUE THREAD

**Issue by hyejungg** [Hous-Release/hous-server#283]
## 📌 Feature Issue

생년월일 optional 하게 수정

## 📝 To-do

- [x] 회원가입 시 생년월일 optional 처리
- [x] 마이페이지, 조회 시 생년월일 optional 처리
- [x] 호미의 탄생 배지 스케줄러 생년월일 optional 처리
