### ISSUE TITLE
동시에 Todo, Rule 추가 시 트랜잭션 이슈로 실패하는 문제 해결

### ISSUE THREAD

**Issue by hyejungg** [Hous-Release/hous-server#294]
## 📌 Feature Issue

동시에 Todo, Rule 추가 시 트랜잭션 이슈로 실패하는 문제 해결

## 📝 To-do

- [x] 동시에 Todo 추가 시 트랜잭션 이슈로 실패하는 문제 해결
- [x] 동시에 Rule 추가 시 트랜잭션 이슈로 실패하는 문제 해결
- [x] 테스트 코드 작성
