### ISSUE TITLE
외래키 삭제 및 cascade 로 삭제하던 로직 수정

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#296]
## 📌 Feature Issue

외래키 삭제 및 cascade 로 삭제하던 로직 수정

## 📝 To-do

- [x] local 에서 사용할 schema.sql, data.sql 작성
- [x] dev yml 파일 jpa ddl-auto 옵션 none 으로 수정 후 github secrets 반영
- [x] dev mysql 외래키 삭제
- [x] prod yml 파일 jpa ddl-auto 옵션 none 으로 수정 후 github secrets 반영
