### ISSUE TITLE
MongoDB Atlas 설정

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#308]
## 📌 Feature Issue

MongoDB Atlas 설정

## 📝 To-do

- [x] 개발 서버 설정
- [x] 배포 서버 설정
- [x] 개발 서버 yml 반영
- [x] 배포 서버 yml 반영
- [x] Transaction 적용 여부 확인 (Rollback)
