### ISSUE TITLE
1.0.7 배포 체크 리스트

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#327]
## 📌 Feature Issue

1.0.7 배포 체크 리스트

## 📝 To-do

- [x] prod 서버 sqs 설정
- [x] prod 서버 mongodb atlas 설정
- [x] prod 서버, github secrets yml 수정
- [x] prod 서버 로그 파일 옮기기
- [x] prod 서버 데이터 작업 전에 백업
- [x] prod 서버 실행 후 일회용 api 호출
- [x] prod 서버 데이터 확인 후 일회용 api 삭제
- [x] prod 서버 데이터 확인 후 불필요한 테이블 삭제
- [x] prod 서버 배포 후 하나 종료

**Comment by hyejungg** [comment]
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/set-cloudwatch-alarms-for-metrics.html

sqs 사용으로 관리포인트가 늘어나서 cloudwatch 설정해도 괜찮을 것 같아서 링크 올려둡니다 ..
