### ISSUE TITLE
1.1.0 Todo 관련 업데이트 작업

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#331]
## 📌 Feature Issue

1.1.0 Todo 관련 업데이트 작업

## 📝 To-do

- [x] Todo 요일별, 멤버별 조회 API 삭제
- [x] Todo 관련 API Swagger 명세서 수정
- [x] Todo 필터별 조회 API 구현
- [x] Todo 추가 가능 여부 조회 API 구현
- [x] Todo 글자 제한 15 -> 20 자 수정
