### ISSUE TITLE
개발 서버 계정 변경

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#341]
## 📌 Feature Issue

개발 서버 계정 변경

## 📝 To-do

- [x] 개발 서버 계정 변경
- [x] code review 자동 설정 추가
- [x] shoutdown graceful 설정 추가
