### ISSUE TITLE
1.1.0 배포 체크리스트

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#349]
## 📌 Feature Issue

1.1.0 배포시 DB 스키마 변경과 같은 변경 사항들 생기면 To-do 에 기록해두기

## 📝 To-do

- [x] 알림 서버 prod yml 파일 github secrets 변경
- [x] dev mysql - feedback 테이블 feedback_type 칼럼 삭제
- [x] dev mysql - personality 테이블 다운로드 이미지 관련 칼럼 두개 추가
- [x] dev mysql - 성향 다운로드 관련 이미지 s3 업로드 후 personality 테이블에 url 추가
- [ ] prod mysql - feedback 테이블 feedback_type 칼럼 삭제
- [ ] prod mysql - personality 테이블 다운로드 이미지 관련 칼럼 두개 추가
- [ ] prod mysql - 성향 다운로드 관련 이미지 s3 업로드 후 personality 테이블에 url 추가
- [ ] prod nginx - 파일 크기 제한 수정하기

**Comment by orijoon98** [comment]
`ALTER TABLE feedback drop feedback_type;`

**Comment by orijoon98** [comment]
```
ALTER TABLE personality add (
    first_download_image_url   varchar(300) not null,
    second_download_image_url  varchar(300) not null);
```

**Comment by orijoon98** [comment]
![image](https://github.com/Hous-Release/hous-server/assets/74812188/f8850dc9-4759-4117-81ee-40845a90dff6)

**Comment by hyejungg** [comment]
240323 
- prod -> dev 로 계정 옮김 (데이터 이전 완료)
- dev 배포 자동화 조심하기 ..
