### ISSUE TITLE
to-do 완료 관련 배지 로직 구현

### ISSUE THREAD

**Issue by orijoon98** [Hous-Release/hous-server#96]
## 📌 Feature Issue

to-do 완료 관련 배지 로직 구현

## 📝 To-do

- [x] 참 잘했어요 배지 로직 구현
- [x] 성실왕 호미 배지 로직 구현
- [x] to-do 마스터 배지 로직 구현
